sudo: required
dist: trusty
language: cpp
compiler: gcc
cache: apt
env:
  - MODE=small MCU=f4 HSE=8000000
  - MODE=small MCU=f4 HSE=8000000 FLOAT=hard
before_install:
  - sudo add-apt-repository ppa:mikepurvis/stm32-staging -y
  - sudo apt-get update
install:
  - sudo apt-get install gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib -y
script:
  - scons mode=$MODE mcu=$MCU hse=$HSE float=$FLOAT install INSTALLDIR=~/usr -j4
  - cd ~/usr && find . | sort
